from enum import StrEnum


class KYCStatus(StrEnum):
    NOT_STARTED = "NOT_STARTED"
    PENDING = "PENDING"
    NEEDS_CORRECTION = "NEEDS_CORRECTION"
    UNDER_REVIEW = "UNDER_REVIEW"
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"
    SUSPENDED = "SUSPENDED"
    EXPIRED = "EXPIRED"


class EvidenceLevel(StrEnum):
    FORMAT_VALID = "FORMAT_VALID"
    MANUALLY_REVIEWED = "MANUALLY_REVIEWED"
    PROVIDER_VERIFIED = "PROVIDER_VERIFIED"


class CardStatus(StrEnum):
    SUBMITTED = "SUBMITTED"
    PENDING_VERIFICATION = "PENDING_VERIFICATION"
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"
    SUSPENDED = "SUSPENDED"
    EXPIRED = "EXPIRED"
    REPLACED = "REPLACED"


class QuoteStatus(StrEnum):
    ACTIVE = "ACTIVE"
    EXPIRED = "EXPIRED"
    CONSUMED = "CONSUMED"


class PaymentStatus(StrEnum):
    CREATED = "CREATED"
    AWAITING_PAYMENT = "AWAITING_PAYMENT"
    RECEIPT_SUBMITTED = "RECEIPT_SUBMITTED"
    AWAITING_RECONCILIATION = "AWAITING_RECONCILIATION"
    LATE_PAYMENT_REVIEW = "LATE_PAYMENT_REVIEW"
    PARTIAL_MATCH = "PARTIAL_MATCH"
    STRONG_MATCH = "STRONG_MATCH"
    CARD_MISMATCH = "CARD_MISMATCH"
    SOURCE_CARD_UNKNOWN = "SOURCE_CARD_UNKNOWN"
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"
    REFUNDED = "REFUNDED"
    EXPIRED = "EXPIRED"


class OrderStatus(StrEnum):
    DRAFT = "DRAFT"
    AWAITING_KYC = "AWAITING_KYC"
    AWAITING_CARD_VERIFICATION = "AWAITING_CARD_VERIFICATION"
    AWAITING_PAYMENT = "AWAITING_PAYMENT"
    PAYMENT_EXPIRED = "PAYMENT_EXPIRED"
    AWAITING_RECONCILIATION = "AWAITING_RECONCILIATION"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    READY_FOR_FULFILLMENT = "READY_FOR_FULFILLMENT"
    PROCESSING = "PROCESSING"
    DELIVERED = "DELIVERED"
    COMPLETED = "COMPLETED"
    WARRANTY = "WARRANTY"
    REFUNDED = "REFUNDED"
    CANCELLED = "CANCELLED"


class RiskStatus(StrEnum):
    CLEAR = "CLEAR"
    REVIEW = "REVIEW"
    BLOCKED = "BLOCKED"
